name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Build
      # run: cargo build --verbose
    - name: Test hello-world
      working-directory: hello-world
      run: cargo test --verbose
    - name: Test reverse-string
      working-directory: reverse-string
      run: cargo test --verbose
    - name: Test gigasecond
      working-directory: gigasecond
      run: cargo test --verbose
    - name: Test clock
      working-directory: clock
      run: cargo test --verbose
    - name: Test anagram
      working-directory: anagram
      run: cargo test --verbose
    - name: Test space-age
      working-directory: space-age
      run: cargo test --verbose
    - name: Test sublist
      working-directory: sublist
      run: cargo test --verbose
